version1/blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, UserPostListView
from . import views
urlpatterns = [
   ## path('', views.home, name='blog-home'),
    path('', PostListView.as_view(),name='blog-home'),
    #ABOVE CODE has to be converted into an actual view
    #by using as_view
    #homepage cause of the ''
    #views.home is function created in the views.py that returns something
    path('about/', views.about, name='blog-about'),
    path('post/<int:pk>/', PostDetailView.as_view(),name='post-detail'), #since i am using a class
    #based view, this will be passed to a class based view
    #ABOVE: pk. why pk? because that's what the detail view expects it to be in order to go grab the
    #specific object ie a specific post
    path('post/new/', PostCreateView.as_view(),name='post-create'),
    #a template is needed for the post create view. but its not going to be named as post_create as we named
    #the detail view(post_detail). in real sense, this will share a templae with the updateview that was created
    #ie post_form
    path('post/<int:pk>/update/', PostUpdateView.as_view(),name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(),name='post-delete'),
    path('user/<str:username>', UserPostListView.as_view(),name='user-posts'),
]

#<app>/<model>_<viewtype>.html

version1/customerpdf/urls.py
from django.urls import path
from .views import render_pdf_view, CustomerpdfListView, customerpdf_render_pdf_view

app_name = 'customerpdf'

urlpatterns = [
    path('', CustomerpdfListView.as_view(), name='customer-list-view'),
    path('test/', render_pdf_view, name = 'test-view'),
    path('pdf/<pk>/', customerpdf_render_pdf_view, name = 'customer-pdf-view'),
]

version1/version1/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as users_views
from convert import views as convert_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from cropimage.views import main_view
from notifications import views as notifications_views
#line/code statement above takes care of user login and logout
#side note- since we are importing multiple views, it's important to use 'as' keyword
#in order to differenciate them
urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', users_views.register, name='register'),
    #below 2 lines as per in notebook
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'), #login view.
    #path('login/', auth_views.LoginView.as_view(template_name='users/login.html',redirect_authenticated_user=True), name='login'),
    # its a built in views. it handes everything except the templates
    #as_view(template_name='users/login.html'), name='login') - tells django where to look for the template
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    #code below tells django which code will go to blogs.url
    path('', include('blog.urls')), #blog.urls=blog/urls
    path('profile/', users_views.profile, name='profile'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),

    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),


    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),



    path('getstarted/', users_views.getstarted, name='getstarted'),

    path('cropimage/', main_view, name="main-view"),
 #   path('notifications/',notifications_views.notifications, name='notifications'),
    path('notifications/', include('notifications.urls')),
    path('convert/', convert_views.convert, name='convert'),
    #path('convert2/', convert_views.convert2, name='convert2'),
    path('customerpdf/', include('customerpdf.urls', namespace='customerpdf')),
    path('store/', include('store.urls')),
]

#below checks the debug settings for the code. it's not compulsory tho
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

version1/customerpdf/models.py
from django.db import models

# Create your models here.

class Customerpdf(models.Model):
    name = models.CharField(max_length=200)
    normal_image = models.ImageField()
    precision_map = models.ImageField()
    description = models.TextField()
    updated = models.DateField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.name)

version1/customerpdf/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.views.generic import ListView
from .models import Customerpdf
# Create your views here.

class CustomerpdfListView(ListView):
    model = Customerpdf
    template_name = 'customerpdf/main.html'

def customerpdf_render_pdf_view(request, *args, **kwargs):
    #return HttpResponse("working")
    #code above- to test if the function works... after it was tested and confirmed,
    #the following code below was added:
    pk = kwargs.get('pk')
    customer = get_object_or_404(Customerpdf, pk=pk)
    template_path = 'customerpdf/pdf2.html'
    context = {'customer': customer}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    # if download:
    # response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    # if display:
    response['Content-Disposition'] = 'filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
        html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
        return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response


def render_pdf_view(request):
    template_path = 'customerpdf/pdf1.html'
    context = {'myvar': 'this is your template context'}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    #if download:
    #response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    #if display:
    response['Content-Disposition'] = 'filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

version1/customerpdf/templates/customerpdf/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Pdfs | {% block title %} {% endblock title %} </title>
  </head>
  <body>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

version1/customerpdf/templates/customerpdf/main.html
{% extends 'customerpdf/base.html' %}

{% block title %}
customers
{% endblock title %}

{% block content %}
    {% for customer in object_list %}
        {{ customer }}
        <a href="{% url 'customerpdf:customer-pdf-view' customer.pk %}"><button class="btn btn-primary">view pdf</button></a>
        <br>
        <hr>
    {% endfor %}
{% endblock content %}

version1/customerpdf/templates/customerpdf/pdf1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {{myvar}}
</body>
</html>

version1/customerpdf/templates/customerpdf/pdf2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
table, th, td {
  border: 1px solid black;
}
</style>
</head>
<body>
    {{customer}}
    <hr>
    {{customer.description}}
    <!--if you want the description to be seen exactly as seen in the admin, do the following:
    after the word 'description', add '|linebreaks'-->
    <br>
    <!--type the following under the <br> (just one) tag in the {{ braces to see the urls of the images:
    customer.normal_image/precision_image, customer.normal_image/precision_image.url
    and customer.normal_image.path-->
<!--    <img src={{customer.precision_map.path}} height="200px">
    <hr>
    <img src={{customer.normal_image.path}} height="200px">-->
<div class="row">
  <div class="column">
    <img src={{customer.precision_map.path}} height="200px">
  </div>
    <br>
  <div class="column">
    <img src={{customer.normal_image.path}} height="200px">
  </div>
</div>
<br>
<table style="width:100%">
  <tr>
    <th><h1>Color</h1></th>
    <th><h1>Meaning</h1></th>
    <th><h1>Prescription</h1></th>
  </tr>
  <tr>
      <td style="background-color:Yellow;"><h2>Yellow</h2></td>
    <td><h2>Dry vegetation and possibility of pest and disease invasion.</h2></td>
      <td><h2>Apply King Quenson Dicamba 700 Wdg</h2></td>
  </tr>
  <tr>
    <td style="background-color:Green;"><h2>Green</h2></td>
    <td><h2>Healthy vegetation</h2></td>
    <td><h2>N/A</h2></td>
  </tr>

  <tr>
    <td style="background-color:Red;"><h2>Red</h2></td>
      <td><h2>Healthy vegetation</h2></td>
    <td><h2>N/A</h2></td>
  </tr>

  <tr>
      <td style="background-color:Cyan;"><h2>Cyan</h2></td>
    <td><h2>Healthy vegetation</h2></td>
    <td><h2>N/A</h2></td>
  </tr>

  <tr>
    <td style="background-color:Blue;"><h2>Blue</h2></td>
    <td><h2>Healthy vegetation</h2></td>
    <td><h2>N/A</h2></td>
  </tr>

  <tr>
    <td style="background-color:Magenta;"><h2>Magenta</h2></td>
    <td><h2>Healthy vegetation</h2></td>
    <td><h2>N/A</h2></td>
  </tr>
</table>
<h3>The products listed in the 'prescription' page can be found in our online shop</h3>

</body>
</html>